# COUNTRY ECONOMY ANALYSIS

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"E:\DATASCIENCE WITH GEN AI & AGENTIC AI\data pandas.xlsx")

In [3]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [4]:
id(df)

2161154341392

In [5]:
pd.__version__

'2.3.3'

In [6]:
len(df)

195

In [7]:
df.shape # dimensions of the dataframe (rows and columns)

(195, 5)

In [8]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [9]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [10]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [13]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [14]:
len(df.columns)

5

In [15]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [16]:
df.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [17]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [18]:
df['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [20]:
df[['BirthRate','InternetUsers']]

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [21]:
df_numerical_data = df[['BirthRate','InternetUsers']]
df_categorical_data= df[['CountryName', 'CountryCode','IncomeGroup']]

In [22]:
df_numerical_data

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [23]:
df_categorical_data

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [24]:
df_numerical_data.head(1)

   BirthRate  InternetUsers
0     10.244           78.9

In [25]:
df_categorical_data.head(1)

  CountryName CountryCode  IncomeGroup
0       Aruba         ABW  High income

In [26]:
print(df.shape)
print(df_numerical_data.columns)
print(df_categorical_data.columns)

(195, 5)
Index(['BirthRate', 'InternetUsers'], dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [28]:
df[:] # all records

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [29]:
df[10:11]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
10  Azerbaijan         AZE       18.3           58.7  Upper middle income

In [30]:
df[0:100:20]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244          78.90          High income
20     Belarus         BLR     12.500          54.17  Upper middle income
40  Costa Rica         CRI     15.022          45.96  Upper middle income
60       Gabon         GAB     30.555           9.20  Upper middle income
80       India         IND     20.291          15.10  Lower middle income

In [31]:
df[2:5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [32]:
df[::5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.900000,High income
5,Argentina,ARG,17.716,59.900000,High income
10,Azerbaijan,AZE,18.300,58.700000,Upper middle income
15,Bangladesh,BGD,20.142,6.630000,Lower middle income
20,Belarus,BLR,12.500,54.170000,Upper middle income
25,Barbados,BRB,12.188,73.000000,High income
30,Canada,CAN,10.900,85.800000,High income
35,Cameroon,CMR,37.236,6.400000,Lower middle income
40,Costa Rica,CRI,15.022,45.960000,Upper middle income
45,Germany,DEU,8.500,84.170000,High income
50,Ecuador,ECU,21.070,40.353684,Upper middle income
55,Ethiopia,ETH,32.925,1.900000,Low income
60,Gabon,GAB,30.555,9.200000,Upper middle income
65,"Gambia, The",GMB,42.525,14.000000,Low income
70,Greenland,GRL,14.500,65.800000,High income
75,Honduras,HND,21.593,17.800000,Lower middle income
80,India,IND,20.291,15.100000,Lower middle income
85,Israel,ISR,21.300,70.800000,High income
90,Kazakhstan,KAZ,22.730,54.000000,Upper middle income
95,"Korea, Rep.",KOR,8.600,84.770000,High income
100,Libya,LBY,21.425,16.500000,Upper middle income
105,Lithuania,LTU,10.100,68.452900,High income
110,Moldova,MDA,12.141,45.000000,Lower middle income
115,Mali,MLI,44.138,3.500000,Low income
120,Mozambique,MOZ,39.705,5.400000,Low income
125,Namibia,NAM,29.937,13.900000,Upper middle income
130,Netherlands,NLD,10.200,93.956400,High income
135,Pakistan,PAK,29.582,10.900000,Lower middle income
140,Poland,POL,9.600,62.849200,High income
145,Qatar,QAT,11.940,85.300000,High income
150,Sudan,SDN,33.477,22.700000,Lower middle income
155,El Salvador,SLV,17.476,23.109300,Lower middle income
160,Suriname,SUR,18.455,37.400000,Upper middle income
165,Seychelles,SYC,18.600,50.400000,High income
170,Tajikistan,TJK,30.792,16.000000,Lower middle income
175,Tunisia,TUN,19.800,43.800000,Upper middle income
180,Uruguay,URY,14.374,57.690000,High income
185,Virgin Islands (U.S.),VIR,10.700,45.300000,High income
190,"Yemen, Rep.",YEM,32.947,20.000000,Lower middle income

In [34]:
df[2:-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
...,...,...,...,...,...
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [35]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [36]:
df[::-5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
189,Samoa,WSM,26.172,15.3000,Lower middle income
184,"Venezuela, RB",VEN,19.842,54.9000,High income
179,Ukraine,UKR,11.100,41.0000,Lower middle income
174,Trinidad and Tobago,TTO,14.590,63.8000,High income
169,Thailand,THA,11.041,28.9400,Upper middle income
164,Swaziland,SWZ,30.093,24.7000,Lower middle income
159,Sao Tome and Principe,STP,34.537,23.0000,Lower middle income
154,Sierra Leone,SLE,36.729,1.7000,Low income
149,Saudi Arabia,SAU,20.576,60.5000,High income
144,French Polynesia,PYF,16.393,56.8000,High income
139,Papua New Guinea,PNG,28.899,6.5000,Lower middle income
134,Oman,OMN,20.419,66.4500,High income
129,Nicaragua,NIC,20.788,15.5000,Lower middle income
124,Malaysia,MYS,16.805,66.9700,Upper middle income
119,Mongolia,MNG,24.275,20.0000,Upper middle income
114,"Macedonia, FYR",MKD,11.222,65.2400,Upper middle income
109,Morocco,MAR,21.023,56.0000,Lower middle income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
99,Liberia,LBR,35.521,3.2000,Low income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
89,Japan,JPN,8.200,89.7100,High income
84,Iceland,ISL,13.400,96.5468,High income
79,Indonesia,IDN,20.297,14.9400,Lower middle income
74,"Hong Kong SAR, China",HKG,7.900,74.2000,High income
69,Grenada,GRD,19.334,35.0000,Upper middle income
64,Guinea,GIN,37.337,1.6000,Low income
59,"Micronesia, Fed. Sts.",FSM,23.511,27.8000,Lower middle income
54,Estonia,EST,10.300,79.4000,High income
49,Algeria,DZA,24.738,16.5000,Upper middle income
44,Czech Republic,CZE,10.200,74.1104,High income
39,Cabo Verde,CPV,21.625,37.5000,Lower middle income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
29,Central African Republic,CAF,34.076,3.5000,Low income
24,Brazil,BRA,14.931,51.0400,Upper middle income
19,Bosnia and Herzegovina,BIH,9.062,57.7900,Upper middle income
14,Burkina Faso,BFA,40.551,9.1000,Low income
9,Austria,AUT,9.400,80.6188,High income
4,United Arab Emirates,ARE,11.044,88.0000,High income

In [38]:
df.isnull() # it will give true when there is mixxing value

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [39]:
df.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [40]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [44]:
df.describe() # descriptive stastics, by default it gives numerical data only

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [48]:
# describe () = it only prits numerucal data

In [49]:
df_categorical_data.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [50]:
df_numerical_data.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [51]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [52]:
df.columns['a','b','c','d','e']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [53]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [56]:
df.BirthRate *df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [57]:
df['myCalc']= df.BirthRate *df.InternetUsers

In [58]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,myCalc
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [74]:
df= df.drop['myCalc', axis == 1]
df

NameError: name 'axis' is not defined

In [69]:
df[df['InternetUsers'] <2]

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [71]:
df[df['BirthRate'] > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [72]:
len(df[df['BirthRate'] > 40])

12

In [75]:
df[(df.BirthRate > 40) & (df.InternetUsers < 2)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income